import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { SessionProvider } from "next-auth/react"
import { useState, useRef } from 'react'
import * as Colyseus from "colyseus.js";
import ColyseusContext from '@/context/ColyseusContext'
import { Observable } from '@babylonjs/core'
import { FormulaPlayer } from '@/types/formula-click'
// import { uniqueNamesGenerator, adjectives, names } from 'unique-names-generator'
// import { useSession, signIn, signOut } from "next-auth/react"
export default function App({
  Component,
  pageProps: { session, ...pageProps }
}: AppProps) {
  const [client, setClient] = useState<Colyseus.Client | null>(null)
  const [room, setRoom] = useState<Colyseus.Room | null>(null)
  const [playerJoined, setPlayerJoined] = useState<boolean>(false)
  const [userName, setUserName] = useState<string | null>(null)
  const onRemotePlayerMsg = useRef<Observable<string>>(new Observable((observer) => console.log("observer added!")))
  const onPlayerTurnMsg = useRef<Observable<boolean>>(new Observable((observer) => console.log("turn based observer added!")))
  const onGameEndMsg = useRef<Observable<boolean>>(new Observable((observer) => console.log("game end observer added!")))
  const playerType = useRef<FormulaPlayer>(FormulaPlayer.local)
  const playerTurn = useRef<boolean>(true)
  const gameEnd = useRef<boolean>(false)
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Click Racer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColyseusContext.Provider value={{ client, setClient, room, setRoom, playerJoined, setPlayerJoined, userName, setUserName, onRemotePlayerMsg, playerType, playerTurn, onPlayerTurnMsg, gameEnd, onGameEndMsg }}>
        <Component {...pageProps} />
      </ColyseusContext.Provider>
    </SessionProvider>
  )
}
