import '@/styles/globals.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { SessionProvider } from "next-auth/react"
import { useState } from 'react'
import * as Colyseus from "colyseus.js";
import ColyseusContext from '@/context/ColyseusContext'
import { uniqueNamesGenerator, adjectives, names } from 'unique-names-generator'
import { useSession, signIn, signOut } from "next-auth/react"
export default function App({
  Component,
  pageProps: { session, ...pageProps }
}: AppProps) {
  const [client, setClient] = useState<Colyseus.Client | null>(null)
  const [room, setRoom] = useState<Colyseus.Room | null>(null)
  const [playerJoined, setPlayerJoined] = useState<boolean>(false)
  const [userName, setUserName] = useState<string | null>(null)
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Formula Golf</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColyseusContext.Provider value={{ client, setClient, room, setRoom, playerJoined, setPlayerJoined, userName, setUserName }}>
        <Component {...pageProps} />
      </ColyseusContext.Provider>
    </SessionProvider>
  )
}
